version: '3'

services:
  app:
    build: ./kashflow
    environment:
      - DATABASE_URL=mysql://user:password@db/kashflow
    depends_on:
      - db

services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app
